apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: ecommerce
  labels:
    app: ecommerce-php
    component: database
type: Opaque
data:
  # DB_USER: admin (base64: YWRtaW4=)
  username: YWRtaW4=
  
  # DB_PASSWORD: admin1234 (base64: YWRtaW4xMjM0)
  password: YWRtaW4xMjM0

---
# Secret adicional para configuración de aplicación
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ecommerce
  labels:
    app: ecommerce-php
    component: application
type: Opaque
data:
  # APP_SECRET para sesiones y CSRF
  app-secret: Y2hhbmdlLXRoaXMtaW4tcHJvZHVjdGlvbi10by1hLXJhbmRvbS1zdHJpbmc=